# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\macir\OneDrive\Dokumenty\Estudios\JS\Python\ProjektNaZaliczenie\venv\intro.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 155)
        Dialog.setMinimumSize(QtCore.QSize(250, 155))
        Dialog.setMaximumSize(QtCore.QSize(250, 155))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\macir\\OneDrive\\Dokumenty\\Estudios\\JS\\Python\\ProjektNaZaliczenie\\venv\\../venv-3.9/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.wybierzLabel = QtWidgets.QLabel(Dialog)
        self.wybierzLabel.setGeometry(QtCore.QRect(10, 0, 221, 50))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(20)
        self.wybierzLabel.setFont(font)
        self.wybierzLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.wybierzLabel.setObjectName("wybierzLabel")
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setGeometry(QtCore.QRect(50, 130, 75, 23))
        self.okButton.setObjectName("okButton")
        self.anulujButton = QtWidgets.QPushButton(Dialog)
        self.anulujButton.setGeometry(QtCore.QRect(130, 130, 75, 23))
        self.anulujButton.setObjectName("anulujButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 90, 231, 41))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioDodaj = QtWidgets.QRadioButton(self.groupBox)
        self.radioDodaj.setGeometry(QtCore.QRect(0, 0, 181, 17))
        self.radioDodaj.setChecked(True)
        self.radioDodaj.setObjectName("radioDodaj")
        self.radioExcel = QtWidgets.QRadioButton(self.groupBox)
        self.radioExcel.setGeometry(QtCore.QRect(0, 20, 201, 17))
        self.radioExcel.setObjectName("radioExcel")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 80, 231, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 50, 231, 41))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioPunkt = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioPunkt.setGeometry(QtCore.QRect(0, 0, 181, 17))
        self.radioPunkt.setChecked(True)
        self.radioPunkt.setObjectName("radioPunkt")
        self.radioPrzed = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioPrzed.setGeometry(QtCore.QRect(0, 20, 181, 17))
        self.radioPrzed.setObjectName("radioPrzed")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Elkasta"))
        self.wybierzLabel.setText(_translate("Dialog", "wybierz typ operacji"))
        self.okButton.setText(_translate("Dialog", "OK"))
        self.anulujButton.setText(_translate("Dialog", "Anuluj"))
        self.radioDodaj.setText(_translate("Dialog", "Dodaj własne rekordy(max. 12)"))
        self.radioExcel.setText(_translate("Dialog", "Importuj tabele z programu Excel"))
        self.radioPunkt.setText(_translate("Dialog", "Szereg rozdzielczy punktowy"))
        self.radioPrzed.setText(_translate("Dialog", "Szereg rozdzielczy przedziałowy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
